---
version: "3.4"
x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 10m
      max-file: "3"

services:

  op-geth:
    image: ghcr.io/bnb-chain/op-geth:latest
    platform: linux/amd64
    restart: unless-stopped
    stop_grace_period: 5m
    entrypoint: /scripts/op-get√h-start.sh
    env_file:
      - ./envs/${NETWORK_NAME}/op-geth.env
      - .env
    ports:
      - ${PORT__OP_GETH:-8545}:8545
    volumes:
      - ./scripts/:/scripts
      - ./jwt.txt:/jwt.txt
      - ./genesis/${NETWORK_NAME}/genesis.json:/genesis.json
      - op_geth:/geth
    <<: *logging

  op-node:
    image: ghcr.io/bnb-chain/op-node:latest
    platform: linux/amd64
    depends_on:
      - op-geth
    restart: unless-stopped
    stop_grace_period: 5m
    entrypoint: /scripts/op-node-start.sh
    env_file:
      - .env
    ports:
      - ${PORT__OP_NODE_P2P:-9003}:9003
      - ${PORT__OP_NODE:-8546}:8546
    volumes:
      - ./scripts/:/scripts
      - ./jwt.txt:/jwt.txt
      - ./genesis/${NETWORK_NAME}/rollup.json:/rollup.json
    <<: *logging

volumes:
  op_geth:
